--- 
 - name: Ensure GDM and gnome-shell are installed
   apt: pkg={{item}}  state={{gnome-shell_pkg_state}}
   with_items:
     - gdm
     - gnome-shell
     - ubuntu-gnome-desktop
     - ubuntu-gnome-default-settings
     - gnome-shell-extensions

 - name: Ensure gnome-shell applications are installed
   apt: pkg={{item}}  state={{gnome-shell_pkg_state}}
   with_items: gnome-shell_apps