---
 - name: Add gnome-shell ppa repository
   apt_repository: repo="ppa:gnome3-team/gnome3"
   register: gnome_shell_ppa_state
   when: gnome_with_ppa

 - name: Add gnome-shell staging ppa repository
   apt_repository: repo="ppa:gnome3-team/gnome3-staging"
   register: gnome_shell_staging_ppa_state
   when: gnome_with_ppa_staging

 - name: Ensure packages are up to date
   apt: update_cache=yes upgrade=dist
   when: gnome_shell_ppa_state|changed or gnome_shell_staging_ppa_state|changed
